In [53]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import signal
from scipy import fftpack
import os
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.grid_search import GridSearchCV
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics

%matplotlib inline

In [28]:
data_frame=pd.read_csv("/Users/thisum/Documents/Personel_Docs/NUS_MSc/Research/MagicHand_Data/posture_data/raw/chamod_q.txt", header=None)
data_frame.loc[:,24].unique()
data_frame.groupby([24]).size()

24
bottle_drinking                     6000
hammer_hammering                    6000
knife_chopping                      6000
knife_cutting                       6000
mug_drinking                        6000
none                                1894
pen_writing                         6000
saw_sawing                          6000
screwdriver_screwing(no-release)    6000
screwdriver_screwing(release)       6000
spoon_stirring                      6000
dtype: int64

In [130]:
train_df = pd.read_csv("../data/pose/per_user/chamod_q_train.txt", header=None)
test_df = pd.read_csv("../data/pose/per_user/chamod_q_test.txt", header=None)

x_test = test_df.loc[:,:14]
y_test = test_df.loc[:,15]

x_train = train_df.loc[:,:14]
y_train = train_df.loc[:,15]

x_combined = x_train.append(x_test)
x_combined =(x_combined-x_combined.mean())/x_combined.std()+0.000001 
x_combined = x_combined.reset_index(drop=True)

x_train = x_combined.loc[:x_train.shape[0]-1, :]
x_test = x_combined.loc[x_train.shape[0]:, :]

train_df.groupby([15]).size()

15
bottle_drinking                     4000
hammer_hammering                    4000
knife                               4000
mug_drinking                        4000
none                                1260
pen_writing                         4000
saw_sawing                          4000
screwdriver_screwing(no-release)    4000
spoon_stirring                      4000
dtype: int64

In [123]:
svm = SVC()
svm.fit(x_train, y_train)
y_pred=svm.predict(x_test)
score = accuracy_score(y_test, y_pred)
print('SVM score: ' + str(score))
print(classification_report(y_test, y_pred))

SVM score: 0.629509379509
                                  precision    recall  f1-score   support

                 bottle_drinking       1.00      1.00      1.00      2000
                hammer_hammering       0.00      0.00      0.00      2000
                           knife       0.57      0.83      0.68      2000
                    mug_drinking       0.97      0.99      0.98      2000
                            none       1.00      1.00      1.00       632
                     pen_writing       0.99      1.00      1.00      2000
                      saw_sawing       0.17      0.10      0.12      2000
screwdriver_screwing(no-release)       0.35      1.00      0.51      2000
                  spoon_stirring       0.00      0.00      0.00      2000

                     avg / total       0.52      0.63      0.55     16632



/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [124]:
rf = RandomForestClassifier()
rf.fit(x_train, y_train)
y_pred=rf.predict(x_test)
score = accuracy_score(y_test, y_pred)
print('RF score: ' + str(score))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

RF score: 0.647907647908
                                  precision    recall  f1-score   support

                 bottle_drinking       0.97      1.00      0.99      2000
                hammer_hammering       0.00      0.00      0.00      2000
                           knife       0.80      0.93      0.86      2000
                    mug_drinking       0.95      0.98      0.97      2000
                            none       1.00      1.00      1.00       632
                     pen_writing       1.00      1.00      1.00      2000
                      saw_sawing       0.45      0.19      0.27      2000
screwdriver_screwing(no-release)       0.29      0.97      0.45      2000
                  spoon_stirring       0.00      0.00      0.00      2000

                     avg / total       0.58      0.65      0.58     16632

[[2000    0    0    0    0    0    0    0    0]
 [   0    0  471   96    0    0  463  970    0]
 [   0   65 1852    0    0    0    4   77    2]
 [   0    0   

In [127]:
clf = MLPClassifier(activation='relu', hidden_layer_sizes=(200,200), max_iter=200000, learning_rate='adaptive', early_stopping=False)
clf.fit(x_train, y_train)
y_pred=clf.predict(x_test)
score = accuracy_score(y_test, y_pred)
print('NN score: ' + str(score))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

NN score: 0.622113997114
                                  precision    recall  f1-score   support

                 bottle_drinking       0.94      1.00      0.97      2000
                hammer_hammering       0.00      0.00      0.00      2000
                           knife       0.81      0.91      0.86      2000
                    mug_drinking       0.86      0.97      0.91      2000
                            none       0.99      1.00      1.00       632
                     pen_writing       1.00      1.00      1.00      2000
                      saw_sawing       0.13      0.10      0.11      2000
screwdriver_screwing(no-release)       0.32      0.88      0.47      2000
                  spoon_stirring       0.00      0.00      0.00      2000

                     avg / total       0.53      0.62      0.56     16632

[[2000    0    0    0    0    0    0    0    0]
 [   0    0  428  324    0    0 1242    6    0]
 [   0   43 1818    0    0    0  128   11    0]
 [   0    0   

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
